[project]
name = "deckworks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Steve", email = "steve.jevon.r@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=3.4.7",
]

[project.scripts]
deckworks = "deckworks:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
