import type { Preset, Theme } from "./types.js";

const sans = '"Source Sans 3", "Anthropic Sans Text", "Helvetica Neue", Arial, sans-serif';
const humanist = '"Plus Jakarta Sans", "Anthropic Sans Text", "Helvetica Neue", Arial, sans-serif';
const serif = '"Newsreader Variable", "Anthropic Sans Text", Georgia, "Times New Roman", serif';
const mono = '"Geist Mono Variable", "Anthropic Sans Text", "SFMono-Regular", Consolas, monospace';

export const themes = {
  minimal: {
    id: "minimal",
    name: "Minimal",
    background: "#fafafa",
    foreground: "#18181b",
    accent: "#18181b",
    muted: "#71717a",
    font: humanist,
  },
  consulting: {
    id: "consulting",
    name: "Consulting",
    background: "#ffffff",
    foreground: "#0f172a",
    accent: "#2563eb",
    muted: "#64748b",
    font: sans,
  },
  corporate: {
    id: "corporate",
    name: "Corporate",
    background: "#ffffff",
    foreground: "#1e293b",
    accent: "#0f766e",
    muted: "#64748b",
    font: sans,
  },
  dark: {
    id: "dark",
    name: "Dark",
    background: "#0b0f1a",
    foreground: "#e5e7eb",
    accent: "#8b5cf6",
    muted: "#94a3b8",
    font: humanist,
  },
  editorial: {
    id: "editorial",
    name: "Editorial",
    background: "#f7f3ec",
    foreground: "#1c1917",
    accent: "#8a5a2b",
    muted: "#78716c",
    font: serif,
  },
  academic: {
    id: "academic",
    name: "Academic",
    background: "#ffffff",
    foreground: "#0f1e3d",
    accent: "#1d4ed8",
    muted: "#64748b",
    font: sans,
  },
  startup: {
    id: "startup",
    name: "Startup",
    background: "#0b1220",
    foreground: "#e6edf7",
    accent: "#14b8a6",
    muted: "#8aa0b8",
    font: humanist,
  },
  mckinsey: {
    id: "mckinsey",
    name: "M*k*ns*y",
    background: "#ffffff",
    foreground: "#051c2c",
    accent: "#2251ff",
    muted: "#4e5b66",
    font: sans,
  },
  deloitte: {
    id: "deloitte",
    name: "D*lo*tt*",
    background: "#ffffff",
    foreground: "#000000",
    accent: "#86bc25",
    muted: "#53565a",
    font: sans,
  },
  c4e: {
    id: "c4e",
    name: "C4e",
    background: "#ffffff",
    foreground: "#0b0b0b",
    accent: "#0000dc",
    muted: "#5a5a5a",
    font: mono,
  },
  travel: {
    id: "travel",
    name: "Travel",
    background: "#f5f7ee",
    foreground: "#1e3a2f",
    accent: "#43a047",
    muted: "#5c6f62",
    font: serif,
  },
} satisfies Record<string, Theme>;

export const presets: Preset[] = [
  { id: "minimal", name: "Minimal", theme: themes.minimal },
  { id: "consulting", name: "Consulting", theme: themes.consulting },
  { id: "corporate", name: "Corporate", theme: themes.corporate },
  { id: "dark", name: "Dark", theme: themes.dark },
  { id: "editorial", name: "Editorial", theme: themes.editorial },
  { id: "academic", name: "Academic", theme: themes.academic },
  { id: "startup", name: "Startup", theme: themes.startup },
  { id: "mckinsey", name: "M*k*ns*y", theme: themes.mckinsey },
  { id: "deloitte", name: "D*lo*tt*", theme: themes.deloitte },
  { id: "c4e", name: "C4e", theme: themes.c4e },
  { id: "travel", name: "Travel", theme: themes.travel },
];
