[project]
name = "remote"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Steve", email = "steve.jevon.r@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.141.1",
    "vercel-sandbox>=0.4.0",
]

[project.scripts]
remote = "remote:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
